---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  tls.crt: | 
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lVTlRVajdja3p2
    NTJwM2xtTXFJSm9NOURGcnE4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xh
    Rzl0WlhkdmNtc3VjblV3SGhjTk1qTXhNVEV4TVRZek5ETTJXaGNOTWpReApNVEV3TVRZek5ETTJX
    akFXTVJRd0VnWURWUVFEREF0b2IyMWxkMjl5YXk1eWRUQ0NBU0l3RFFZSktvWklodmNOCkFRRUJC
    UUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNbGpMc3Q0aGVheW1pUzB2M3pGcURuN1ZzU2ZpNjNqVmxTZkla
    d0oKcXBtRDQ2TnVocEZqeUhvbFFnZ1Y3SEVhMkFJZWw5ZEt2bEwrZ2FsS2xMNWQ4V3RWamVjZDhi
    NnNyOXp2UmIwdwpEcEd1ZTBaaks0ZW1jMlBhc2Vyd2tsNkZuR21nd21CUGhaaHh3cWJLd2tHNnFW
    dENjRU9naVdacXdtMjU2cnlPCnZMbWc2ZW9WMDc3L09ncXl6YlVhWGRUa1NaRGVZaXFJTENJK1V2
    cGRFZXVFa0N1cys2QlJ1anNVN0RSWE5RQ0QKelNiMWhoaFlmOUhOQmZ1WHk0TnQ3UUVnVDgyQ2JY
    MWpwMmJGdFJNeFovcVJmd3d4djMxbDF4V0NvTlM2alM3bQp5cG5OMHF2TGkrVDZjaGdKczR1YmRZ
    dVI5MTRpYzEwL0syY0syUFNVZjV2ZUM3a0NBd0VBQWFOck1Ha3dIUVlEClZSME9CQllFRkFrUzlr
    cGJ4MEg2QW1BNldLZ2Z3WXBZVDNBTk1COEdBMVVkSXdRWU1CYUFGQWtTOWtwYngwSDYKQW1BNldL
    Z2Z3WXBZVDNBTk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0ZnWURWUjBSQkE4d0RZSUxhRzl0Wlhk
    dgpjbXN1Y25Vd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDNGU2UGVRbkRab3doV1ptWC9NOENS
    aGJjUWpiRHV4ClNDRXZyTXFON2tHTTR4Z1NHUmZ2bXVEVmpMbWRXeDJLMGNzZmhFb0FBRUNmT3NM
    eDdycUVkb2h4UFFSZGs1ckcKL3prbm9BV1krNzg0dEJrUElrMk53L1ZiQldlUGxUOGtOVVBVd05p
    amlMWk51T2ZkZFdFckFlS08yWnN6R1U4MwpxZXlmODdQUnFNdzFBNXoybnZqMENTQW9NRSs1YVJo
    UmRGeG5pc1hseFBDcWd4dVN5TGwva1d0MDI0V2FsbkxUCmVDNkpqZlluK1o1QXdneWtoQmd2RjJw
    V2ZrKy9ici9sRC9Tem5ZYzhYMXludkZRYUNRbkZSQmhYdDlJc0lVM08KS3FiWmZSOHRsZWpuRjAx
    OVhzR2F6c2x1R0k3VVVhR2ZDOHFJUW9sYU5GSzZaQll2MU9Lc2JzVT0KLS0tLS1FTkQgQ0VSVElG
    SUNBVEUtLS0tLQo=
  tls.key: | 
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRREpZeTdMZUlYbXNwb2sKdEw5OHhhZzUrMWJFbjR1dDQxWlVu
    eUdjQ2FxWmcrT2pib2FSWThoNkpVSUlGZXh4R3RnQ0hwZlhTcjVTL29HcApTcFMrWGZGclZZM25I
    ZkcrcksvYzcwVzlNQTZScm50R1l5dUhwbk5qMnJIcThKSmVoWnhwb01KZ1Q0V1ljY0ttCnlzSkJ1
    cWxiUW5CRG9JbG1hc0p0dWVxOGpyeTVvT25xRmRPKy96b0tzczIxR2wzVTVFbVEzbUlxaUN3aVBs
    TDYKWFJIcmhKQXJyUHVnVWJvN0ZPdzBWelVBZzgwbTlZWVlXSC9SelFYN2w4dURiZTBCSUUvTmdt
    MTlZNmRteGJVVApNV2Y2a1g4TU1iOTlaZGNWZ3FEVXVvMHU1c3FaemRLcnk0dmsrbklZQ2JPTG0z
    V0xrZmRlSW5OZFB5dG5DdGowCmxIK2IzZ3U1QWdNQkFBRUNnZ0VBRlVBaGluZnp6VFd3ZlVvVFlM
    T3N2ajJPMk4yckRCVE9vY3hPN0J1N0JFcisKQk50ZldNMHFOUFZrZzl6b1g4RUE1U3hjUW13UkxF
    bk4zZExRWWt3Z2N2NktwRVl0SWIwd0s0U1dHOUlMMzRTRgpYcGFOVzltTkdJN1ZzbUJqV1pVSXZi
    Nm9kQ2hBQlNlUDdqQzhFZHFFRDJ5eDB2a0lOcVh5VVVqS2c4NGVEUXBGCllQeHNuanZ1MG0wVWJH
    Y3VtSXYrUzVBUVN5V3hVbHZkUmdKd1dKQm90WkpKSHBDRVhOa0I3VVEzejAxckNPTGcKL0tBR05O
    d2pva1RQTWdYbVFhTjFxc0R5b0E1NHovT2V4SDAxUURjdXViVTBFeis1d1VsWlhCMzVLQ09oWEFP
    RQphQXhiSHZGS1JLNkNwNzY2ZG9mZ2Q3L09FTlVnNXRlSnF1NlVwTTBBMXdLQmdRRHJrYWFLM05M
    cXlwUWY0L0J0CmRWLzFpTDc3R24wNW16VEhUWnJ3RHN4Sm9FVjN5RWt1QlhHNXovN1g2YTRIWUpt
    SGRTVEtESHI1QWpzelgvN1YKeUo5bUdNdnpiTGJSVHJGZU4vUnNJZFZyS0xIcExEeWFQV1pzeE43
    NWZGUGJXNVBWVEx0UVpRNWtqVkRnVVhQSgpuc1UxV2VIQ3loSzY1aS9wdFR5NXNPMXB6d0tCZ1FE
    YTJwa3F3MlAyNlZwRDlzQ0N5bDN0ZUhEL0NKREp4TGlzCm0zYUNYbWRxNFBRdGJpTTBIR29SUk5z
    U2lKb3ltT3d2aFIvTTZWaFRWS3RlMjlzR2xGLytDaURWdU9helpHbm0KSWJRVXpMNURrb0dIai9o
    Ulh0RGRvQi9Lb09mV0J6Mkw0NnYyVFN4ZFI4T2FmTGZab2d3ZFg0TGQ1aEdoS2p3UgorTUlmdGNI
    Nzl3S0JnRDhFaThVQ0pmcGhqeGFvNTV5Z2xiY2RpZG1xMEcwa3RBM05HUEczUTdjK2hOYnlZWUZL
    Ck80NDFzanNZYkZIVTZiMXUvUlNBR2pXYS96TlRMdDBKK25wWmo5WGk4MVV5OUFmOGVBcWxVbTZF
    U0hQVVBiSVYKVXQwdUhXZ29kbFpzUFRRR2Z1V1c0eTdMRHlPekpvSjlVc3hlNnlJczVLM1MvbVpL
    OFovTFVQZkpBb0dBVUx1egpKUU5QTFJhSUplb3d1ZzdNOTMwbXNlNEcrMmVHZUtZZzRaYlJyNnVz
    WjlYcFJwLzB3TW9WeHBCOTBZeDRGRStYCm00KzQ5WVNXY3pmSFpIWDNzMDhwTGE0MzdKVnVPMmJU
    ZDVqUDF6MkVhdTNCUE1NdGFaUllKZmVWam02OVZZMTMKTWpUbDJNTlFkUHp0Rld1aDdIUC9Zcndz
    WkxlZjBVRmkyeS9CajZFQ2dZQUY3RjR2UUZ2UTRwM0RqV3RkbmtZNwpEVERaSHE1V3Nic3FUaEJl
    N3pVdmQrSFA0Ty93ckhETEsxd2ZtT3NLb1lxNWFDa1U5Vjl5Z21lSFFsMHlxVW9CClJLWW41SEp1
    WklFR29na3F0NWhwQ2lkNWcwZ21TeWFaREJUa2JyejBhUzBGa0hDcVRocXpwSGt1RTFSZ3BINXEK
    alAzcW02bUFaL0xsQWR2WGdMTmNQZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls