---
- name: Configuration Kubernetes nodes on Almalinux 9
  hosts: all
  become: true
  vars:
    sysctl_param:
      - net.bridge.bridge-nf-call-iptables
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-ip6tables
    packages:
      - kubelet
      - kubeadm
      - kubectl

  tasks:
    - name: Disable selinux
      ansible.posix.selinux:
        state: disabled

    - name: Turn off swap
      ansible.builtin.command: swapoff -a

    # - name: Configure hosts file
    #   ansible.builtin.lineinfile:
    #     dest: /etc/hosts
    #     regexp: '.*{{ item }}$'
    #     line: '{{ hostvars[item].ansible_host }} {{item}}'
    #     state: present
    #   with_items: '{{ groups["all"] }}'

    - name: Load modules
      ansible.builtin.shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Add configuration for automatically modules loaded
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/containerd.conf
        create: true
        block: |
          overlay
          br_netfilter

    - name: Setup sysctl params
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/k8s.conf
      loop:
        "{{ sysctl_param }}"

    - name: Add official Docker Repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
  
    - name: Install the containerd package
      ansible.builtin.dnf:
        name: containerd
        state: present
  
    - name: Create a configuration file for containerd and set it to default
      ansible.builtin.shell: |
        mkdir -p /etc/containerd
        containerd config default | sudo tee /etc/containerd/config.toml
  
    - name: Set cgroupdriver to systemd
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        line: SystemdCgroup = true
  
    - name: Restart containerd package
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true
  
    - name: Add the Kubernetes repository
      ansible.builtin.blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        create: true
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg          
  
    - name: Install all Kubernetes modules (kubelet, kubeadm, kubectl)
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
  
    - name: Enable kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: true