---
masters:
  hosts:
    master-node-1:
      ansible_host: 84.201.159.177
      ansible_user: cloud-user
    master-node-2:
      ansible_host: 84.201.156.114
      ansible_user: cloud-user
    master-node-3:
      ansible_host: 51.250.95.223
      ansible_user: cloud-user

workers:
  hosts:
    worker-node-1:
      ansible_host: 51.250.84.63
      ansible_user: cloud-user
    worker-node-2:
      ansible_host: 51.250.79.208
      ansible_user: cloud-user
      
vip:
  hosts:
    proxy-master:
      ansible_host: 51.250.93.37
      ansible_user: cloud-user
    # proxy-slave:
      # ansible_host: 158.160.114.137
      # ansible_user: cloud-user

cluster:
  children:
    masters:
    workers:

all:
  children:
    masters:
    workers:
    vip: