---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myuser-binding
  namespace: app
subjects:
- kind: User 
  name: myuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: myuser-role
  apiGroup: rbac.authorization.k8s.io