---

- name: Install MicroK8S on Almalinux 9
  hosts: all
#  gather_facts: false
  become: true
  tasks:
    - name: Disable selinux
      ansible.posix.selinux:
        state: disabled

    - name: Install epel-release
      ansible.builtin.dnf:
        name:
         - epel-release
        state: present

    - name: Install snapd
      ansible.builtin.dnf:
        name:
         - snapd
        state: present

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link

    - name: Start and enable snapd.socket
      ansible.builtin.systemd:
        name: snapd.socket
        state: started
        enabled: true
    
    - name: Add to path
      ansible.builtin.copy:
        content: "PATH=$PATH:/var/lib/snapd/snap/bin"
        dest: /etc/profile.d/snap.sh
        mode: "0644"

    - name: Install MicroK8S
      community.general.snap:
        name: microk8s
        classic: true

    - name: Add user to microk8s group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: true

    - name: Setting external connection
      ansible.builtin.lineinfile:
        path: /var/snap/microk8s/current/certs/csr.conf.template
      #  mode: '0644'
        regexp: '^IP.3'
        insertafter: '#MOREIPS'
        line: 'IP.3 = 0.0.0.0'

  #  - name: Service status snapd.socket
  #    ansible.builtin.systemd:
  #      name: snapd.socket
  #    register: snap_status

  #  - debug:
  #      msg: snap_status.ActiveState